# Generated by Django 4.2.7 on 2023-11-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusDriver',
        ),
    ]
