# Generated by Django 4.2.7 on 2023-11-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_delete_busdriver'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owners',
        ),
    ]
