# Generated by Django 4.2.7 on 2023-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
    ]
