# Generated by Django 4.2.7 on 2023-11-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busdriver',
            table='drivers',
        ),
    ]
