# Generated by Django 4.2.7 on 2023-11-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_table'),
        ('driver', '0002_alter_busdriver_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdriver',
            name='id_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
    ]
